version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: Oracle123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - backend

  dotnet-app:
    image: hellomesq/abrigogerenciamento
    container_name: abrigogerenciamento
    depends_on:
      - oracle-db
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "User Id=system;Password=Oracle123;Data Source=oracle-db:1521/XEPDB1"
    networks:
      - backend

volumes:
  oracle-data:

networks:
  backend:
    driver: bridge
